AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'gemfiles/*'
    - 'spec/dummy/db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'tmp/**/*'

Naming/FileName:
  Exclude:
    - lib/jsonapi-authorization.rb
    - Appraisals

Layout/LineLength:
  Enabled: true
  Max: 100
  Exclude:
    - spec/requests/**/*.rb
    - jsonapi-authorization.gemspec

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Metrics/MethodLength:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
  EnforcedStyle: space

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/WordArray:
  MinSize: 2

Metrics/ModuleLength:
  Enabled: false

Style/SingleLineBlockParams:
  Methods:
    - reduce:
        - acc
        - obj
    - inject:
        - acc
        - obj

Style/Alias:
  EnforcedStyle: prefer_alias_method
