Metrics/LineLength:
  Enabled: true
  Max: 100

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: true

Metrics/MethodLength:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false
  EnforcedStyle: space

Style/IndentHash:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/WordArray:
  MinSize: 2

Metrics/ModuleLength:
  Enabled: false

Style/SingleLineBlockParams:
  Methods:
    - reduce:
        - acc
        - obj
    - inject:
        - acc
        - obj
