inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'gemfiles/*'
    - 'spec/dummy/db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'tmp/**/*'

# TODO: Define a spec.required_ruby_version when shipping a new version
Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/jsonapi-authorization.rb
    - Appraisals

Layout/LineLength:
  Enabled: true
  Max: 100
  Exclude:
    - spec/requests/**/*.rb
    - jsonapi-authorization.gemspec

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
