# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        gemfile:
          - rails_5_2_pundit_1
          - rails_5_2_pundit_2
          - rails_6_0_pundit_1
          - rails_6_0_pundit_2
        ruby-version: [ '2.5', '2.7' ]
        bundler-version: [ '1.11' ]
        include:
          # Include Rails 6.0 / Ruby 3.0 combo
          - gemfile: rails_6_0_pundit_1
            ruby-version: '3.0'
            bundler-version: '2.1.4'
          - gemfile: rails_6_0_pundit_2
            ruby-version: '3.0'
            bundler-version: '2.1.4'
    continue-on-error: true
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          bundler: ${{ matrix.bundler-version }}
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rake
